use std::fs;
#[cfg(unix)]
use std::os::unix::process::{CommandExt, ExitStatusExt};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};

use tempfile::NamedTempFile;

use crate::certgen::CaPair;
use crate::config::Config;
use crate::errors::{KeyclawError, CODE_MITM_NOT_EFFECTIVE};
use crate::gitleaks_rules::RuleSet;
use crate::pipeline::Processor;
use crate::proxy::Server;
use crate::vault::Store;

pub(super) fn run_proxy_foreground(cfg: &Config, processor: Arc<Processor>, ca: CaPair) -> i32 {
    let allowed_hosts = Config::allowed_hosts("all", cfg);

    let mut proxy_server = Server::new(
        cfg.proxy_listen_addr.clone(),
        allowed_hosts,
        processor,
        ca.cert_pem.clone(),
        ca.key_pem,
    );
    proxy_server.max_body_bytes = cfg.max_body_bytes;
    proxy_server.body_timeout = cfg.detector_timeout;

    let running_proxy = match proxy_server.start() {
        Ok(p) => p,
        Err(err) => {
            super::print_error(&err);
            return 1;
        }
    };

    let proxy_url = format!("http://{}", running_proxy.addr);

    let keyclaw_dir = crate::certgen::keyclaw_dir();
    let ca_path = keyclaw_dir.join("ca.crt");

    let pid_path = keyclaw_dir.join("proxy.pid");
    let pid = std::process::id();
    let _ = fs::write(&pid_path, pid.to_string());

    let env_path = keyclaw_dir.join("env.sh");
    let current_exe = std::env::current_exe().unwrap_or_else(|_| PathBuf::from("keyclaw"));
    let env_content = render_proxy_env_script(pid, &proxy_url, &ca_path, &current_exe, &pid_path);
    if let Err(e) = fs::write(&env_path, &env_content) {
        crate::logging::error(&format!("failed to write env file: {e}"));
        return 1;
    }

    crate::logging::info(&format!("proxy listening on {}", running_proxy.addr));
    crate::logging::info("source ~/.keyclaw/env.sh in any shell to route through keyclaw");
    crate::logging::info("press Ctrl-C to stop");

    let mut signals = match signal_hook::iterator::Signals::new([
        signal_hook::consts::SIGINT,
        signal_hook::consts::SIGTERM,
    ]) {
        Ok(s) => s,
        Err(e) => {
            crate::logging::error(&format!("failed to register signals: {e}"));
            return 1;
        }
    };

    let _ = (&mut signals).into_iter().next();

    let _ = fs::remove_file(&pid_path);
    drop(running_proxy);

    crate::logging::info("proxy stopped");
    0
}

pub(super) fn run_proxy_detached(cfg: &Config) -> Result<i32, KeyclawError> {
    let keyclaw_dir = crate::certgen::keyclaw_dir();
    fs::create_dir_all(&keyclaw_dir)
        .map_err(|e| KeyclawError::uncoded(format!("create keyclaw dir: {e}")))?;

    let pid_path = keyclaw_dir.join("proxy.pid");
    let env_path = keyclaw_dir.join("env.sh");
    let log_path = keyclaw_dir.join("proxy.log");
    let _ = fs::remove_file(&pid_path);
    let _ = fs::remove_file(&env_path);

    let current_exe = std::env::current_exe()
        .map_err(|e| KeyclawError::uncoded(format!("resolve current executable: {e}")))?;
    let log_file = std::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(&log_path)
        .map_err(|e| {
            KeyclawError::uncoded(format!("open proxy log {}: {e}", log_path.display()))
        })?;
    let log_file_err = log_file
        .try_clone()
        .map_err(|e| KeyclawError::uncoded(format!("clone proxy log handle: {e}")))?;

    let mut child = Command::new(current_exe)
        .arg("proxy")
        .arg("--foreground")
        .envs(std::env::vars())
        .stdin(Stdio::null())
        .stdout(Stdio::from(log_file))
        .stderr(Stdio::from(log_file_err))
        .spawn()
        .map_err(|e| KeyclawError::uncoded(format!("start detached proxy: {e}")))?;

    wait_for_detached_proxy_ready(&mut child, &pid_path, &env_path, &log_path)?;

    crate::logging::info("proxy running in background");
    crate::logging::info("source ~/.keyclaw/env.sh in any shell to route through keyclaw");
    crate::logging::info("stop it later with: kill \"$(cat ~/.keyclaw/proxy.pid)\"");
    crate::logging::info(&format!("proxy log file: {}", log_path.display()));

    let _ = cfg;
    Ok(0)
}

pub(super) fn render_proxy_env_script(
    pid: u32,
    proxy_url: &str,
    ca_path: &Path,
    current_exe: &Path,
    pid_path: &Path,
) -> String {
    let exe_name = current_exe
        .file_name()
        .and_then(|name| name.to_str())
        .filter(|name| !name.trim().is_empty())
        .unwrap_or("keyclaw");
    let pid_value = shell_single_quote(&pid.to_string());
    let pid_file = shell_single_quote(&pid_path.display().to_string());
    let exe_name = shell_single_quote(exe_name);
    let proxy_url = shell_single_quote(proxy_url);
    let ca_path = shell_single_quote(&ca_path.display().to_string());

    format!(
        r#"# Generated by keyclaw proxy (PID {pid})
# Source this in any shell to route through keyclaw.
# Safe to keep in .bashrc — exports only while the same keyclaw proxy instance is still active.
keyclaw_proxy_pid={pid_value}
keyclaw_proxy_pid_file={pid_file}
keyclaw_proxy_exe_name={exe_name}

keyclaw_proxy_active() {{
  if ! kill -0 "$keyclaw_proxy_pid" 2>/dev/null; then
    return 1
  fi

  if ! command -v ps >/dev/null 2>&1; then
    return 1
  fi

  keyclaw_proxy_comm="$(ps -ww -o comm= -p "$keyclaw_proxy_pid" 2>/dev/null || true)"
  if [ "$keyclaw_proxy_comm" != "$keyclaw_proxy_exe_name" ]; then
    return 1
  fi

  keyclaw_proxy_args="$(ps -ww -o args= -p "$keyclaw_proxy_pid" 2>/dev/null || true)"
  case "$keyclaw_proxy_args" in
    *" proxy"|*" proxy "*) return 0 ;;
  esac

  return 1
}}

if keyclaw_proxy_active; then
  export HTTP_PROXY={proxy_url}
  export HTTPS_PROXY={proxy_url}
  export ALL_PROXY={proxy_url}
  export http_proxy={proxy_url}
  export https_proxy={proxy_url}
  export all_proxy={proxy_url}
  export SSL_CERT_FILE={ca_path}
  export REQUESTS_CA_BUNDLE={ca_path}
  export NODE_EXTRA_CA_CERTS={ca_path}
else
  rm -f "$keyclaw_proxy_pid_file"
  unset HTTP_PROXY HTTPS_PROXY ALL_PROXY http_proxy https_proxy all_proxy
  unset SSL_CERT_FILE REQUESTS_CA_BUNDLE NODE_EXTRA_CA_CERTS
fi
"#,
    )
}

fn shell_single_quote(value: &str) -> String {
    let escaped = value.replace('\'', r#"'\''"#);
    format!("'{escaped}'")
}

#[derive(Clone)]
pub(super) struct Runner {
    config: Config,
    processor: Arc<Processor>,
}

impl Runner {
    pub(super) fn new(config: Config, processor: Arc<Processor>) -> Self {
        Self { config, processor }
    }

    pub(super) fn launch(
        &mut self,
        tool: &str,
        child_args: Vec<String>,
    ) -> Result<i32, KeyclawError> {
        let allowed_hosts = Config::allowed_hosts(tool, &self.config);
        // In mitm mode with a TTY, redirect proxy logs to a file so they
        // do not interleave with the child CLI's TUI output.
        if unsafe { libc::isatty(libc::STDIN_FILENO) } != 0 {
            let log_path = crate::certgen::keyclaw_dir().join("mitm.log");
            if let Err(e) = crate::proxy::set_log_file(&log_path) {
                crate::logging::warn(&format!(
                    "failed to open log file {}: {e}",
                    log_path.display()
                ));
            }
        }

        if let Some(reason) = launcher_bypass_risk(
            &std::env::var("NO_PROXY").unwrap_or_default(),
            &allowed_hosts,
        ) {
            crate::logging::warn_with_code(CODE_MITM_NOT_EFFECTIVE, &reason);
            if self.config.require_mitm_effective {
                return Err(KeyclawError::coded(CODE_MITM_NOT_EFFECTIVE, reason));
            }
        }

        let ca = crate::certgen::ensure_ca()?;

        let mut proxy_server = Server::new(
            self.config.proxy_listen_addr.clone(),
            allowed_hosts,
            self.processor.clone(),
            ca.cert_pem.clone(),
            ca.key_pem,
        );
        proxy_server.max_body_bytes = self.config.max_body_bytes;
        proxy_server.body_timeout = self.config.detector_timeout;

        let running_proxy = proxy_server.start()?;

        let proxy_url = if self.config.proxy_url.trim().is_empty()
            || running_proxy.addr != self.config.proxy_listen_addr.trim()
        {
            format!("http://{}", running_proxy.addr)
        } else {
            self.config.proxy_url.clone()
        };
        let running_proxy = Arc::new(Mutex::new(Some(running_proxy)));

        let (ca_path, _temp_ca) = resolve_ca_cert_path(&self.config.ca_cert_path)?;
        let (command, args) = build_command(tool, child_args);

        let mut cmd = Command::new(command);
        cmd.args(args)
            .stdin(Stdio::inherit())
            .stdout(Stdio::inherit())
            .stderr(Stdio::inherit());

        for (k, v) in with_proxy_env(proxy_url, ca_path.as_deref()) {
            cmd.env(k, v);
        }

        #[cfg(unix)]
        {
            unsafe {
                cmd.pre_exec(|| {
                    libc::setpgid(0, 0);
                    Ok(())
                });
            }
        }

        let mut child = cmd
            .spawn()
            .map_err(|e| KeyclawError::uncoded(format!("start child process: {e}")))?;

        #[cfg(unix)]
        let original_pgrp = unsafe {
            let child_pid = child.id() as libc::pid_t;
            let original = libc::tcgetpgrp(libc::STDIN_FILENO);
            if original >= 0 {
                set_foreground_process_group(libc::STDIN_FILENO, child_pid);
            }
            original
        };

        #[cfg(unix)]
        let signal_thread = {
            let pid = child.id() as i32;
            let done = Arc::new(AtomicBool::new(false));
            let done_for_thread = Arc::clone(&done);
            let proxy_for_thread = Arc::clone(&running_proxy);
            std::thread::spawn(move || {
                let mut signals = match signal_hook::iterator::Signals::new([
                    signal_hook::consts::SIGINT,
                    signal_hook::consts::SIGTERM,
                    signal_hook::consts::SIGHUP,
                    signal_hook::consts::SIGQUIT,
                ]) {
                    Ok(s) => s,
                    Err(_) => return,
                };

                while !done_for_thread.load(Ordering::SeqCst) {
                    for sig in signals.pending() {
                        unsafe {
                            libc::killpg(pid, sig);
                        }

                        if let Ok(mut guard) = proxy_for_thread.lock() {
                            if let Some(proxy) = guard.take() {
                                drop(proxy);
                            }
                        }

                        if sig == signal_hook::consts::SIGINT || sig == signal_hook::consts::SIGTERM
                        {
                            std::thread::spawn(move || {
                                std::thread::sleep(Duration::from_secs(2));
                                let still_alive = unsafe { libc::kill(pid, 0) == 0 };
                                if still_alive {
                                    unsafe {
                                        libc::killpg(pid, libc::SIGKILL);
                                    }
                                }
                            });
                        }
                    }

                    std::thread::sleep(Duration::from_millis(50));
                }

                signals.handle().close();
            });

            done
        };

        let status = child
            .wait()
            .map_err(|e| KeyclawError::uncoded(format!("wait child process: {e}")))?;

        #[cfg(unix)]
        {
            signal_thread.store(true, Ordering::SeqCst);
            if original_pgrp >= 0 {
                set_foreground_process_group(libc::STDIN_FILENO, original_pgrp);
            }
        }

        std::thread::sleep(Duration::from_millis(50));

        let intercept_count = {
            let mut guard = running_proxy
                .lock()
                .map_err(|_| KeyclawError::uncoded("proxy state lock poisoned"))?;
            let count = guard
                .as_ref()
                .map(|proxy| proxy.intercept_count())
                .unwrap_or(0);
            let _ = guard.take();
            count
        };

        if intercept_count == 0 {
            let reason = "no intercepted requests observed; traffic may be bypassing proxy";
            crate::logging::warn_with_code(CODE_MITM_NOT_EFFECTIVE, reason);
            if self.config.require_mitm_effective {
                if let Some(code) = status.code() {
                    return Ok(code);
                }
                return Err(KeyclawError::coded(CODE_MITM_NOT_EFFECTIVE, reason));
            }
        }

        if let Some(code) = status.code() {
            return Ok(code);
        }

        #[cfg(unix)]
        {
            if let Some(signal) = status.signal() {
                return Ok(128 + signal);
            }
        }

        Ok(1)
    }
}

pub(super) fn configure_unsafe_logging(cfg: &Config) {
    crate::proxy::set_unsafe_log(cfg.unsafe_log);
    if cfg.unsafe_log {
        crate::logging::warn("unsafe logging enabled; secrets may appear in logs");
    }
}

pub(super) fn build_processor(cfg: &Config) -> Result<Arc<Processor>, KeyclawError> {
    let passphrase =
        crate::vault::resolve_vault_passphrase(&cfg.vault_path, cfg.vault_passphrase.as_deref())?;
    let vault = Arc::new(Store::new(cfg.vault_path.clone(), passphrase));

    let ruleset = load_runtime_ruleset(cfg)?;

    crate::logging::info(&format!("{} gitleaks rules loaded", ruleset.rules.len()));

    Ok(Arc::new(Processor {
        vault: Some(vault),
        ruleset: Arc::new(ruleset),
        max_body_size: cfg.max_body_bytes,
        strict_mode: cfg.fail_closed,
    }))
}

fn load_runtime_ruleset(cfg: &Config) -> Result<RuleSet, KeyclawError> {
    match cfg.gitleaks_config_path.as_deref() {
        Some(path) => match RuleSet::from_file(path) {
            Ok(ruleset) => {
                if ruleset.skipped_rules > 0 {
                    crate::logging::warn(&format!(
                        "loaded {} custom gitleaks rules from {}, skipped {} invalid rule(s)",
                        ruleset.rules.len(),
                        path.display(),
                        ruleset.skipped_rules
                    ));
                }
                Ok(ruleset)
            }
            Err(err) => {
                crate::logging::warn(&format!(
                    "failed to load custom rules from {}: {err}",
                    path.display()
                ));
                crate::logging::warn("falling back to bundled rules");
                load_bundled_ruleset()
            }
        },
        None => load_bundled_ruleset(),
    }
}

fn load_bundled_ruleset() -> Result<RuleSet, KeyclawError> {
    let ruleset = RuleSet::bundled()
        .map_err(|err| KeyclawError::uncoded(format!("load bundled gitleaks rules: {err}")))?;
    if ruleset.skipped_rules > 0 {
        crate::logging::info(&format!(
            "loaded {} bundled gitleaks rules, skipped {} invalid rule(s)",
            ruleset.rules.len(),
            ruleset.skipped_rules
        ));
    }
    Ok(ruleset)
}

fn with_proxy_env(proxy_url: String, ca_path: Option<&str>) -> Vec<(String, String)> {
    let mut env = std::env::vars().collect::<std::collections::HashMap<_, _>>();

    for key in [
        "HTTP_PROXY",
        "HTTPS_PROXY",
        "ALL_PROXY",
        "http_proxy",
        "https_proxy",
        "all_proxy",
    ] {
        env.insert(key.to_string(), proxy_url.clone());
    }

    if let Some(path) = ca_path {
        for key in ["SSL_CERT_FILE", "REQUESTS_CA_BUNDLE", "NODE_EXTRA_CA_CERTS"] {
            env.insert(key.to_string(), path.to_string());
        }
    }

    env.into_iter().collect()
}

fn resolve_ca_cert_path(
    explicit_path: &str,
) -> Result<(Option<String>, Option<NamedTempFile>), KeyclawError> {
    if !explicit_path.trim().is_empty() {
        super::doctor::validate_ca_cert_file(Path::new(explicit_path))?;
        return Ok((Some(explicit_path.to_string()), None));
    }

    let ca_path = crate::certgen::keyclaw_dir().join("ca.crt");
    if ca_path.exists() {
        return Ok((Some(ca_path.to_string_lossy().to_string()), None));
    }

    let ca = crate::certgen::ensure_ca()?;
    let temp = NamedTempFile::new()
        .map_err(|e| KeyclawError::uncoded(format!("create temp CA file: {e}")))?;
    fs::write(temp.path(), ca.cert_pem.as_bytes())
        .map_err(|e| KeyclawError::uncoded(format!("write temp CA file: {e}")))?;

    Ok((Some(temp.path().to_string_lossy().to_string()), Some(temp)))
}

#[cfg(unix)]
fn set_foreground_process_group(fd: libc::c_int, pgrp: libc::pid_t) {
    unsafe {
        let previous = libc::signal(libc::SIGTTOU, libc::SIG_IGN);
        libc::tcsetpgrp(fd, pgrp);
        libc::signal(libc::SIGTTOU, previous);
    }
}

fn build_command(tool: &str, child_args: Vec<String>) -> (String, Vec<String>) {
    let mut child_args = child_args;
    if child_args
        .first()
        .map(|first| first.eq_ignore_ascii_case(tool))
        .unwrap_or(false)
    {
        child_args.remove(0);
    }
    (tool.to_string(), child_args)
}

fn wait_for_detached_proxy_ready(
    child: &mut std::process::Child,
    pid_path: &Path,
    env_path: &Path,
    log_path: &Path,
) -> Result<(), KeyclawError> {
    let deadline = Instant::now() + Duration::from_secs(60);

    while Instant::now() < deadline {
        if pid_matches_child(pid_path, child.id())? && env_path.exists() {
            return Ok(());
        }

        if let Some(status) = child
            .try_wait()
            .map_err(|e| KeyclawError::uncoded(format!("check detached proxy status: {e}")))?
        {
            if let Some(detail) = detached_proxy_failure_detail(log_path) {
                return Err(KeyclawError::uncoded(format!(
                    "detached proxy exited early with status {status}: {detail}"
                )));
            }
            return Err(KeyclawError::uncoded(format!(
                "detached proxy exited early with status {status}; inspect {}",
                log_path.display()
            )));
        }

        std::thread::sleep(Duration::from_millis(50));
    }

    Err(KeyclawError::uncoded(format!(
        "detached proxy did not become ready; inspect {}",
        log_path.display()
    )))
}

fn pid_matches_child(pid_path: &Path, child_pid: u32) -> Result<bool, KeyclawError> {
    let pid = match fs::read_to_string(pid_path) {
        Ok(pid) => pid,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => return Ok(false),
        Err(err) => {
            return Err(KeyclawError::uncoded(format!(
                "read proxy pid file {}: {err}",
                pid_path.display()
            )))
        }
    };

    Ok(pid.trim() == child_pid.to_string())
}

fn detached_proxy_failure_detail(log_path: &Path) -> Option<String> {
    let log = fs::read_to_string(log_path).ok()?;
    log.lines()
        .rev()
        .map(str::trim)
        .find(|line| !line.is_empty())
        .map(|line| {
            line.strip_prefix("keyclaw error: ")
                .or_else(|| line.strip_prefix("keyclaw warn: "))
                .or_else(|| line.strip_prefix("keyclaw info: "))
                .unwrap_or(line)
                .to_string()
        })
}

#[derive(Debug, PartialEq, Eq)]
enum NoProxyEntry {
    Wildcard,
    Host {
        raw: String,
        host: String,
        is_suffix: bool,
        has_port: bool,
    },
}

impl NoProxyEntry {
    fn parse(raw: &str) -> Option<Self> {
        let raw = raw.trim();
        if raw.is_empty() {
            return None;
        }
        if raw == "*" {
            return Some(Self::Wildcard);
        }

        let (host, has_port) = split_host_port(raw);
        let host = host.to_lowercase();
        let is_suffix = host.starts_with('.');
        let host = host.trim_start_matches('.').to_string();
        if host.is_empty() {
            return None;
        }

        Some(Self::Host {
            raw: raw.to_string(),
            host,
            is_suffix,
            has_port,
        })
    }

    fn match_reason(&self, intercepted_host: &str) -> Option<String> {
        match self {
            Self::Wildcard => Some("NO_PROXY=*".to_string()),
            Self::Host {
                raw,
                host,
                is_suffix,
                has_port,
            } => {
                let exact = intercepted_host == host;
                let suffix = intercepted_host.ends_with(&format!(".{host}"));
                if !(exact || *is_suffix && suffix) {
                    return None;
                }

                if *is_suffix || *has_port {
                    Some(format!(
                        "NO_PROXY includes {raw} (matches {intercepted_host})"
                    ))
                } else {
                    Some(format!("NO_PROXY includes {raw}"))
                }
            }
        }
    }
}

pub(super) fn launcher_bypass_risk(no_proxy: &str, hosts: &[String]) -> Option<String> {
    let entries = no_proxy
        .split(',')
        .filter_map(NoProxyEntry::parse)
        .collect::<Vec<_>>();

    for host in hosts
        .iter()
        .filter_map(|host| normalize_no_proxy_host(host))
    {
        for entry in &entries {
            if let Some(reason) = entry.match_reason(&host) {
                return Some(reason);
            }
        }
    }

    None
}

fn normalize_no_proxy_host(host: &str) -> Option<String> {
    let host = host.trim();
    if host.is_empty() {
        return None;
    }
    Some(split_host_port(host).0.to_lowercase())
}

fn split_host_port(value: &str) -> (&str, bool) {
    let value = value.trim();
    if value.matches(':').count() == 1 {
        if let Some((host, port)) = value.rsplit_once(':') {
            if !host.is_empty() && port.chars().all(|ch| ch.is_ascii_digit()) {
                return (host, true);
            }
        }
    }
    (value, false)
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;
    use std::time::Duration;

    use crate::config::Config;
    use crate::logging::LogLevel;

    fn test_config(vault_path: PathBuf) -> Config {
        Config {
            proxy_listen_addr: "127.0.0.1:8877".into(),
            proxy_url: "http://127.0.0.1:8877".into(),
            ca_cert_path: String::new(),
            vault_path,
            vault_passphrase: None,
            fail_closed: true,
            max_body_bytes: 2 * 1024 * 1024,
            detector_timeout: Duration::from_secs(4),
            known_codex_hosts: Vec::new(),
            known_claude_hosts: Vec::new(),
            gitleaks_config_path: None,
            log_level: LogLevel::Info,
            unsafe_log: false,
            require_mitm_effective: true,
        }
    }

    #[test]
    fn load_runtime_ruleset_falls_back_to_bundled_rules_when_custom_file_fails() {
        let temp = tempfile::tempdir().expect("tempdir");
        let mut cfg = test_config(temp.path().join("vault.enc"));
        cfg.gitleaks_config_path = Some(temp.path().join("missing-gitleaks.toml"));

        let ruleset = super::load_runtime_ruleset(&cfg).expect("fallback to bundled rules");

        assert!(
            !ruleset.rules.is_empty(),
            "bundled fallback should still load shipped rules"
        );
    }
}
