use std::fs;
use std::io::{self, Read, Write};
use std::path::PathBuf;
use std::process::{Command, Stdio};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};
use std::time::Duration;

#[cfg(unix)]
use std::os::unix::process::{CommandExt, ExitStatusExt};

use tempfile::NamedTempFile;

use crate::config::Config;
use crate::detector::{EmbeddedDetector, GitleaksDetector};
use crate::errors::{code_of, KeyclawError, CODE_MITM_NOT_EFFECTIVE};
use crate::pipeline::Processor;
use crate::policy::{Executor, Mode};
use crate::proxy::Server;
use crate::vault::Store;

pub fn run_cli(args: Vec<String>) -> i32 {
    if args.is_empty() {
        print_usage(&mut io::stderr());
        return 2;
    }

    let cfg = Config::from_env();
    let processor = build_processor(&cfg);

    if std::env::var("KEYCLAW_UNSAFE_LOG")
        .map(|v| matches!(v.trim(), "1" | "true" | "yes"))
        .unwrap_or(false)
    {
        crate::proxy::set_unsafe_log(true);
        eprintln!("keyclaw: ⚠ UNSAFE_LOG enabled — secrets will appear in logs!");
    }

    match args[0].as_str() {
        "mitm" => run_mitm(&cfg, processor, &args[1..]),
        "proxy" => run_proxy(&cfg, processor),
        "rewrite-json" => run_rewrite_json(processor),
        "doctor" => run_doctor(&cfg),
        _ => {
            print_usage(&mut io::stderr());
            2
        }
    }
}

fn run_mitm(cfg: &Config, processor: Arc<Processor>, args: &[String]) -> i32 {
    if args.is_empty() {
        eprintln!("usage: keyclaw mitm <codex|claude> [-- child args]");
        return 2;
    }

    let tool = args[0].trim().to_lowercase();
    if tool != "codex" && tool != "claude" {
        eprintln!("unsupported tool \"{}\"", tool);
        return 2;
    }

    let child_args = if let Some(idx) = args[1..].iter().position(|a| a == "--") {
        args[1 + idx + 1..].to_vec()
    } else {
        args[1..].to_vec()
    };

    let mut runner = Runner::new(cfg.clone(), processor);
    match runner.launch(&tool, child_args) {
        Ok(code) => code,
        Err(err) => {
            print_error(&err);
            1
        }
    }
}

fn run_proxy(cfg: &Config, processor: Arc<Processor>) -> i32 {
    let allowed_hosts = Config::allowed_hosts("all", cfg);

    let ca = match crate::certgen::ensure_ca() {
        Ok(ca) => ca,
        Err(e) => {
            eprintln!("keyclaw: {e}");
            return 1;
        }
    };

    let mut proxy_server = Server::new(
        cfg.proxy_listen_addr.clone(),
        allowed_hosts,
        processor,
        ca.cert_pem.clone(),
        ca.key_pem,
    );
    proxy_server.max_body_bytes = cfg.max_body_bytes;
    proxy_server.body_timeout = cfg.detector_timeout;

    let running_proxy = match proxy_server.start() {
        Ok(p) => p,
        Err(err) => {
            print_error(&err);
            return 1;
        }
    };

    let proxy_url = format!("http://{}", running_proxy.addr);

    // CA cert already written by certgen::ensure_ca()
    let keyclaw_dir = crate::certgen::keyclaw_dir();
    let ca_path = keyclaw_dir.join("ca.crt");

    let pid_path = keyclaw_dir.join("proxy.pid");
    let pid = std::process::id();
    let _ = fs::write(&pid_path, pid.to_string());

    let env_path = keyclaw_dir.join("env.sh");
    let env_content = format!(
        r#"# Generated by keyclaw proxy (PID {pid})
# Source this in any shell to route through keyclaw.
# Safe to keep in .bashrc — auto-disables when the proxy is not running.
if kill -0 {pid} 2>/dev/null; then
  export HTTP_PROXY="{proxy_url}"
  export HTTPS_PROXY="{proxy_url}"
  export ALL_PROXY="{proxy_url}"
  export http_proxy="{proxy_url}"
  export https_proxy="{proxy_url}"
  export all_proxy="{proxy_url}"
  export SSL_CERT_FILE="{ca}"
  export REQUESTS_CA_BUNDLE="{ca}"
  export NODE_EXTRA_CA_CERTS="{ca}"
else
  unset HTTP_PROXY HTTPS_PROXY ALL_PROXY http_proxy https_proxy all_proxy
  unset SSL_CERT_FILE REQUESTS_CA_BUNDLE NODE_EXTRA_CA_CERTS
fi
"#,
        ca = ca_path.display(),
    );
    if let Err(e) = fs::write(&env_path, &env_content) {
        eprintln!("keyclaw: failed to write env file: {e}");
        return 1;
    }

    eprintln!("keyclaw: proxy listening on {}", running_proxy.addr);
    eprintln!("keyclaw: source ~/.keyclaw/env.sh in any shell to route through keyclaw");
    eprintln!("keyclaw: press Ctrl-C to stop");

    // Block on signals
    let mut signals = match signal_hook::iterator::Signals::new([
        signal_hook::consts::SIGINT,
        signal_hook::consts::SIGTERM,
    ]) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("keyclaw: failed to register signals: {e}");
            return 1;
        }
    };

    for _sig in &mut signals {
        break;
    }

    // Cleanup — keep env.sh (it self-disables via PID check)
    let _ = fs::remove_file(&pid_path);
    drop(running_proxy);

    eprintln!("\nkeyclaw: proxy stopped");
    0
}



fn run_rewrite_json(processor: Arc<Processor>) -> i32 {
    let mut input = Vec::new();
    if io::stdin().read_to_end(&mut input).is_err() {
        eprintln!("failed to read stdin");
        return 1;
    }

    match processor.rewrite_and_evaluate(&input) {
        Ok(result) => {
            if io::stdout().write_all(&result.body).is_err() {
                eprintln!("failed to write stdout");
                return 1;
            }
            0
        }
        Err(err) => {
            print_error(&err);
            1
        }
    }
}

fn run_doctor(cfg: &Config) -> i32 {
    let mut issues = Vec::new();

    if cfg.proxy_url.trim().is_empty() {
        issues.push("proxy URL is empty".to_string());
    }

    if cfg.require_mitm_effective {
        if let Some(reason) = launcher_bypass_risk(
            &std::env::var("NO_PROXY").unwrap_or_default(),
            &Config::allowed_hosts("all", cfg),
        ) {
            issues.push(format!("{}: {}", CODE_MITM_NOT_EFFECTIVE, reason));
        }
    }

    if issues.is_empty() {
        println!("doctor: ok");
        return 0;
    }

    for issue in issues {
        println!("doctor: {issue}");
    }

    1
}

#[derive(Clone)]
pub struct Runner {
    config: Config,
    processor: Arc<Processor>,
}

impl Runner {
    pub fn new(config: Config, processor: Arc<Processor>) -> Self {
        Self { config, processor }
    }

    pub fn launch(&mut self, tool: &str, child_args: Vec<String>) -> Result<i32, KeyclawError> {
        let allowed_hosts = Config::allowed_hosts(tool, &self.config);

        if let Some(reason) = launcher_bypass_risk(
            &std::env::var("NO_PROXY").unwrap_or_default(),
            &allowed_hosts,
        ) {
            eprintln!("keyclaw warning: {} ({})", CODE_MITM_NOT_EFFECTIVE, reason);
            if self.config.require_mitm_effective {
                return Err(KeyclawError::coded(CODE_MITM_NOT_EFFECTIVE, reason));
            }
        }

        let ca = crate::certgen::ensure_ca()?;

        let mut proxy_server = Server::new(
            self.config.proxy_listen_addr.clone(),
            allowed_hosts,
            self.processor.clone(),
            ca.cert_pem.clone(),
            ca.key_pem,
        );
        proxy_server.max_body_bytes = self.config.max_body_bytes;
        proxy_server.body_timeout = self.config.detector_timeout;

        let running_proxy = proxy_server.start()?;

        let proxy_url = if self.config.proxy_url.trim().is_empty()
            || running_proxy.addr != self.config.proxy_listen_addr.trim()
        {
            format!("http://{}", running_proxy.addr)
        } else {
            self.config.proxy_url.clone()
        };
        let running_proxy = Arc::new(Mutex::new(Some(running_proxy)));

        let (ca_path, _temp_ca) = resolve_ca_cert_path(&self.config.ca_cert_path)?;
        let (command, args) = build_command(tool, child_args);

        let mut cmd = Command::new(command);
        cmd.args(args)
            .stdin(Stdio::inherit())
            .stdout(Stdio::inherit())
            .stderr(Stdio::inherit());

        for (k, v) in with_proxy_env(proxy_url, ca_path.as_deref()) {
            cmd.env(k, v);
        }

        #[cfg(unix)]
        {
            unsafe {
                cmd.pre_exec(|| {
                    libc::setpgid(0, 0);
                    Ok(())
                });
            }
        }

        let mut child = cmd
            .spawn()
            .map_err(|e| KeyclawError::uncoded(format!("start child process: {e}")))?;

        #[cfg(unix)]
        let signal_thread = {
            let pid = child.id() as i32;
            let done = Arc::new(AtomicBool::new(false));
            let done_for_thread = Arc::clone(&done);
            let proxy_for_thread = Arc::clone(&running_proxy);
            std::thread::spawn(move || {
                let mut signals = match signal_hook::iterator::Signals::new([
                    signal_hook::consts::SIGINT,
                    signal_hook::consts::SIGTERM,
                    signal_hook::consts::SIGHUP,
                    signal_hook::consts::SIGQUIT,
                ]) {
                    Ok(s) => s,
                    Err(_) => return,
                };

                while !done_for_thread.load(Ordering::SeqCst) {
                    for sig in signals.pending() {
                        unsafe {
                            libc::killpg(pid, sig);
                        }

                        if let Ok(mut guard) = proxy_for_thread.lock() {
                            if let Some(proxy) = guard.take() {
                                drop(proxy);
                            }
                        }

                        if sig == signal_hook::consts::SIGINT
                            || sig == signal_hook::consts::SIGTERM
                        {
                            std::thread::spawn(move || {
                                std::thread::sleep(Duration::from_secs(2));
                                let still_alive = unsafe { libc::kill(pid, 0) == 0 };
                                if still_alive {
                                    unsafe {
                                        libc::killpg(pid, libc::SIGKILL);
                                    }
                                }
                            });
                        }
                    }

                    std::thread::sleep(Duration::from_millis(50));
                }

                let _ = signals.handle().close();
            });

            done
        };

        let status = child
            .wait()
            .map_err(|e| KeyclawError::uncoded(format!("wait child process: {e}")))?;

        #[cfg(unix)]
        {
            signal_thread.store(true, Ordering::SeqCst);
        }

        std::thread::sleep(Duration::from_millis(50));

        let intercept_count = {
            let mut guard = running_proxy
                .lock()
                .map_err(|_| KeyclawError::uncoded("proxy state lock poisoned"))?;
            let count = guard.as_ref().map(|proxy| proxy.intercept_count()).unwrap_or(0);
            let _ = guard.take();
            count
        };

        if intercept_count == 0 {
            let reason = "no intercepted requests observed; traffic may be bypassing proxy";
            eprintln!("keyclaw warning: {} ({})", CODE_MITM_NOT_EFFECTIVE, reason);
            if self.config.require_mitm_effective {
                if let Some(code) = status.code() {
                    return Ok(code);
                }
                return Err(KeyclawError::coded(CODE_MITM_NOT_EFFECTIVE, reason));
            }
        }

        if let Some(code) = status.code() {
            return Ok(code);
        }

        #[cfg(unix)]
        {
            if let Some(signal) = status.signal() {
                return Ok(128 + signal);
            }
        }

        Ok(1)
    }
}

fn build_processor(cfg: &Config) -> Arc<Processor> {
    let vault_path = std::env::var("KEYCLAW_VAULT_PATH")
        .ok()
        .filter(|v| !v.trim().is_empty())
        .map(PathBuf::from)
        .unwrap_or_else(|| default_vault_path());

    let passphrase = std::env::var("KEYCLAW_VAULT_PASSPHRASE")
        .ok()
        .filter(|v| !v.trim().is_empty())
        .unwrap_or_else(|| "keyclaw-default-passphrase".to_string());

    let vault = Arc::new(Store::new(vault_path, passphrase));

    let gitleaks = Arc::new(GitleaksDetector::new(
        cfg.gitleaks_binary.clone(),
        cfg.detector_timeout,
    ));
    let embedded = Arc::new(EmbeddedDetector::new());

    let mode = match std::env::var("KEYCLAW_POLICY_MODE") {
        Ok(v) if v.eq_ignore_ascii_case("warn") => Mode::Warn,
        _ => Mode::Block,
    };

    let policy = Arc::new(Executor::new(
        Some(gitleaks),
        Some(embedded),
        mode,
        cfg.fail_closed,
    ));

    Arc::new(Processor {
        vault: Some(vault),
        policy: Some(policy),
        max_body_size: cfg.max_body_bytes,
        strict_mode: cfg.fail_closed,
    })
}

fn default_vault_path() -> PathBuf {
    let home = std::env::var("HOME").unwrap_or_else(|_| ".".to_string());
    PathBuf::from(home).join(".keyclaw").join("vault.enc")
}

fn with_proxy_env(proxy_url: String, ca_path: Option<&str>) -> Vec<(String, String)> {
    let mut env = std::env::vars().collect::<std::collections::HashMap<_, _>>();

    for key in [
        "HTTP_PROXY",
        "HTTPS_PROXY",
        "ALL_PROXY",
        "http_proxy",
        "https_proxy",
        "all_proxy",
    ] {
        env.insert(key.to_string(), proxy_url.clone());
    }

    if let Some(path) = ca_path {
        for key in ["SSL_CERT_FILE", "REQUESTS_CA_BUNDLE", "NODE_EXTRA_CA_CERTS"] {
            env.insert(key.to_string(), path.to_string());
        }
    }

    env.into_iter().collect()
}

fn resolve_ca_cert_path(
    explicit_path: &str,
) -> Result<(Option<String>, Option<NamedTempFile>), KeyclawError> {
    if !explicit_path.trim().is_empty() {
        return Ok((Some(explicit_path.to_string()), None));
    }

    // Use the cert from ~/.keyclaw/ca.crt (written by certgen::ensure_ca)
    let ca_path = crate::certgen::keyclaw_dir().join("ca.crt");
    if ca_path.exists() {
        return Ok((Some(ca_path.to_string_lossy().to_string()), None));
    }

    // Fallback: generate and write to temp
    let ca = crate::certgen::ensure_ca()?;
    let temp = NamedTempFile::new()
        .map_err(|e| KeyclawError::uncoded(format!("create temp CA file: {e}")))?;
    fs::write(temp.path(), ca.cert_pem.as_bytes())
        .map_err(|e| KeyclawError::uncoded(format!("write temp CA file: {e}")))?;

    Ok((Some(temp.path().to_string_lossy().to_string()), Some(temp)))
}

fn build_command(tool: &str, child_args: Vec<String>) -> (String, Vec<String>) {
    if let Some((first, rest)) = child_args.split_first() {
        return (first.clone(), rest.to_vec());
    }
    (tool.to_string(), Vec::new())
}

pub fn launcher_bypass_risk(no_proxy: &str, hosts: &[String]) -> Option<String> {
    let mut set = std::collections::HashSet::new();
    for item in no_proxy.split(',') {
        let v = item.trim().to_lowercase();
        if !v.is_empty() {
            set.insert(v);
        }
    }

    if set.contains("*") {
        return Some("NO_PROXY=*".to_string());
    }

    for host in hosts {
        if set.contains(&host.to_lowercase()) {
            return Some(format!("NO_PROXY includes {host}"));
        }
    }

    None
}

fn print_error(err: &KeyclawError) {
    let code = code_of(err);
    let msg = crate::logscrub::scrub(&err.to_string());
    if let Some(code) = code {
        eprintln!("{}: {}", code, msg);
    } else {
        eprintln!("{}", msg);
    }
}

fn print_usage(w: &mut dyn Write) {
    let _ = writeln!(w, "Usage:");
    let _ = writeln!(w, "  keyclaw proxy                      # start global proxy daemon");
    let _ = writeln!(w, "  keyclaw mitm codex -- [codex args]");
    let _ = writeln!(w, "  keyclaw mitm claude -- [claude args]");
    let _ = writeln!(w, "  keyclaw rewrite-json < payload.json");
    let _ = writeln!(w, "  keyclaw doctor");
}
